# Debug Likelihood

I hope to debug my current likelihood implementation. The challenge is to set the right data structure of the covariance data.

## Check Output Shape

In [5]:
root = '/global/common/software/des/jesteves/y3_cluster_cpp/y3_buzzard/datablock_0/'
print(root)
print('')
!ls /global/common/software/des/jesteves/y3_cluster_cpp/y3_buzzard/datablock_0/

/global/common/software/des/jesteves/y3_cluster_cpp/y3_buzzard/datablock_0/

avgwp		      correlationfunction      mass_function	 priors
cdm_baryon_power_lin  cosmological_parameters  matter_power_lin  recfast
cdm_baryon_power_nl   distances		       matter_power_nl	 shear
cluster_abundance     growth_parameters        mstar		 sigmacritinv
cmb_cl		      kappa		       numbercounts	 wp


In [8]:
import numpy as np
def get_block(model,col,dtype=None):
    return np.genfromtxt(root+'%s/%s.txt'%(model.lower(), col),dtype=dtype)

In [56]:
shear = get_block("shear", "shear_cen")

In [73]:
shear.shape

(12, 100)

In [61]:
sh1 = shear.reshape(3,4,100)

In [67]:
a = np.array([[0,0,0],[1,1,1]])
a.shape

(2, 3)

In [68]:
a.flatten()

array([0, 0, 0, 1, 1, 1])

In [69]:
b = np.array([[[0,0,0],[1,1,1]],[[2,2,2],[3,3,3]]])
b.shape

(2, 2, 3)

In [71]:
b.flatten()

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [76]:
b[0]

array([[0, 0, 0],
       [1, 1, 1]])

In [74]:
Rp = get_block("avgwp", "gridpoints")[:30,2]
avgWp = get_block("avgwp", "vals")
# avgWp = avgWp.reshape(4*3,Rp.size)

In [75]:
avgWp.shape

(4, 90)

In [17]:
avgWp[0][:30]

array([-10304748.39311901, -10309828.03874237, -10313362.84529974,
       -10315353.53879782, -10315807.73100757, -10314461.60738287,
       -10311105.97043097, -10305708.21011803, -10298246.5211094 ,
       -10288620.86360609, -10276660.28735881, -10261700.02764738,
       -10244118.03970216, -10223116.94310054, -10198827.83464191,
       -10170748.68299378, -10138504.87429577, -10275686.20482635,
       -10812290.59801063, -10766741.1480565 , -10715607.42546337,
       -10658107.88792727, -10593407.78616001, -10521384.09614461,
       -10440999.34201537, -10351829.97392236, -10252502.64680875,
       -10140831.50642867, -10016736.21647215,  -9878852.47482065])

In [18]:
avgWp[0][30:]

array([-10215770.1353181 , -10260064.78323385, -10301719.40280471,
       -10340351.68004999, -10376610.33946764, -10410271.24277403,
       -10440185.25779942, -10467486.14658764, -10491015.45994996,
       -10511057.31547363, -10527298.69597513, -10539399.59113617,
       -10546748.82453769, -10549511.1731586 , -10547153.26854534,
       -10539318.0557429 , -10525278.48377422, -10758765.37928249,
       -11578483.40986962, -11544323.49873465, -11501757.42650528,
       -11449667.7526211 , -11386594.70427154, -11312531.71195111,
       -11226154.99105121, -11126540.31037572, -11011965.4290253 ,
       -10879425.19302916, -10728324.48442962, -10556572.07185464,
        -1393727.10832033,  -1468157.69335366,  -1539994.15298917,
        -1609325.94511245,  -1675910.63099887,  -1740940.73411262,
        -1802187.9885343 ,  -1862097.32728204,  -1918084.38315958,
        -1971083.90321223,  -2020819.79687149,  -2068081.05303381,
        -2109763.11575584,  -2148640.83131452,  -2183333.97275

## Read Covariance

In [ ]:
# variation
# (l0,z0); (l0, z1); (l0, z2)
# (l1, z0); (l1, z1); (l1, z2)
# ...

In [23]:
nc = get_block("numbercounts", "vals")
nc

array([[ 70890.79279959, 103981.57861766,  82375.77825787],
       [  9446.65346982,  11905.36071806,   8286.10214458],
       [  4206.363367  ,   4663.29941435,   2723.61047946],
       [  3039.40580702,   2200.62476933,    834.16409416]])

In [25]:
ncf = nc.flatten()
ncf

array([ 70890.79279959, 103981.57861766,  82375.77825787,   9446.65346982,
        11905.36071806,   8286.10214458,   4206.363367  ,   4663.29941435,
         2723.61047946,   3039.40580702,   2200.62476933,    834.16409416])

In [28]:
np.repeat(ncf, 3) # with 3 radii

array([ 70890.79279959,  70890.79279959,  70890.79279959, 103981.57861766,
       103981.57861766, 103981.57861766,  82375.77825787,  82375.77825787,
        82375.77825787,   9446.65346982,   9446.65346982,   9446.65346982,
        11905.36071806,  11905.36071806,  11905.36071806,   8286.10214458,
         8286.10214458,   8286.10214458,   4206.363367  ,   4206.363367  ,
         4206.363367  ,   4663.29941435,   4663.29941435,   4663.29941435,
         2723.61047946,   2723.61047946,   2723.61047946,   3039.40580702,
         3039.40580702,   3039.40580702,   2200.62476933,   2200.62476933,
         2200.62476933,    834.16409416,    834.16409416,    834.16409416])

In [30]:
cov = np.sqrt(ncf)

In [54]:
## with radii
blocks = []
for i in range(3):
    blocks.append(list(np.full((3,3), i+1)))

In [55]:
from scipy import linalg

linalg.block_diag(*blocks)

array([[1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 2, 2, 0, 0, 0],
       [0, 0, 0, 2, 2, 2, 0, 0, 0],
       [0, 0, 0, 2, 2, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 3, 3],
       [0, 0, 0, 0, 0, 0, 3, 3, 3],
       [0, 0, 0, 0, 0, 0, 3, 3, 3]])